# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cldkctl < Formula
  desc "A CLI tool for managing cloud infrastructure"
  homepage "https://github.com/Lintasarta/cldkctl"
  version "0.0.3"
  license "MIT"

  depends_on "go"
  depends_on "yq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.3/cldkctl-0.0.3_Darwin_x86_64.tar.gz"
      sha256 "86247ff6c16f02ee582fe73c9c2c7f9854c0a33db95cb471de304c289dd9db27"

      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.3/cldkctl-0.0.3_Darwin_arm64.tar.gz"
      sha256 "567f8777ce5c61af17fe02261384860331e4454426bb698b4bdb8504be7f216d"

      def install
        bin.install "cldkctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.3/cldkctl-0.0.3_Linux_x86_64.tar.gz"
      sha256 "6fde56ff7de1d917988f1aef5e0c9a1953b334c69ec709648ad58953de124eb2"
      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.3/cldkctl-0.0.3_Linux_arm64.tar.gz"
      sha256 "9b224fca5e0e070bf80e2679ec1341585b524ff659e16bc5b04bf73d5440bb34"
      def install
        bin.install "cldkctl"
      end
    end
  end

  test do
    system "#{bin}/cldkctl --version"
  end
end
