# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cldkctl < Formula
  desc "A CLI tool for managing cloud infrastructure"
  homepage "https://github.com/Lintasarta/cldkctl"
  version "0.0.2"
  license "MIT"

  depends_on "go"
  depends_on "yq"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.2/cldkctl-0.0.2_Darwin_x86_64.tar.gz"
      sha256 "9f75791b66729e613023f12e835a4d234a73196cc3e194f414c18f791ad729c6"

      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.2/cldkctl-0.0.2_Darwin_arm64.tar.gz"
      sha256 "aad2b464b961561d4ddfda35d139f21ebab855b906315456b2ce7bc64d28bea0"

      def install
        bin.install "cldkctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.2/cldkctl-0.0.2_Linux_x86_64.tar.gz"
      sha256 "b9cd7990b86197c05d7bf66dd89d98d7a9382bd27a6161d9a8d47214756064be"
      def install
        bin.install "cldkctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Lintasarta/cldkctl/releases/download/v0.0.2/cldkctl-0.0.2_Linux_arm64.tar.gz"
      sha256 "57c03c1c382ad390277de9ab3cce0bc7472cc15c0ac1204c58709527a5950c4c"
      def install
        bin.install "cldkctl"
      end
    end
  end

  test do
    system "#{bin}/cldkctl --version"
  end
end
